[addressbooks]
[[posteo]]
path = ~/.local/contacts/clara.kofler@posteo.com/default

[general]
debug = no
default_action = list
editor = nvim, -i, NONE
merge_editor = vimdiff

[contact table]
#display names by first of last name
display = first_name
# show uid table column: yes/no
show_uids = yes
#sort by first or last name: first_name / last_name / formatted_name
sort = last_name
# localize dates: yes / no
localize_dates = yes
# set a comma seperated list of preferred phone number types in descending priority
preferred_phone_number_type = pref, cell, home
# set a csv list of preferred email address types in descending priority
preferred_email_address_type = pref, work, home

